### PR TITLE
Unzip password protected files

### PR DESCRIPTION
**Pull request by hitesh96db**
Added two new API's for android only --

1. ```unzipWithPassword(zipFilePath, unzipPath, password)```
The response of this API is different from `unzip`. This returns a list of filenames that have been extracted out, which is more informative than just the unzipPath (that's already known before-hand).

2. ```isPasswordProtected(zipFilePath)``` 
This simply checks if the zip file is encrypted or not.

Both of these APIs use [Zip4j](http://www.lingala.net/zip4j/) under the hood. I've made some changes in the Example app as well to test out the functionality, which is part of the PR. I won't be able to work on the changes required for iOS, so that still remains a to-do.

### CODE REVIEW

**Comment by plrthink** [comment]
cool, I would accept it now but release when the iOS version is also supported.

also, I agree with your api suggestions and would make changes to it.

**Comment by hitesh96db** [comment]
Java supports method overloading and Javascript doesn't, which is why the javascript method is named as `unzipWithPassword` but the Java method is simply `unzip`. I had done this intentionally, I hope this clears any confusion around it.

**Comment by brystfire08** [comment]
I got an error: ` RNZipArchive got 4 arguments, expected 5` before changing it

**Comment by hitesh96db** [comment]
Strange, worked for me. What react version did you try this with?

**Pull request merged**
