### PR TITLE
chore(ios): Update SSZipArchive to 2.5.5

### PR DESCRIPTION
**Pull request by vomchik**
Fix for this [issue](https://github.com/mockingbot/react-native-zip-archive/issues/302)

### CODE REVIEW

**Comment by plrthink** [comment]
OK, would release this right now.

**Comment by vomchik** [comment]
Damn, it looks like we need to revert it(

**Comment by plrthink** [comment]
@balmasich @vomchik Yes, I just found out that. Although it's a breaking change, I think we have to since it's needed for submitting to the app store.

**Comment by plrthink** [comment]
According to forks' feedback on this change, I just realized we should not update the deployment target internally, this makes many apps, that can't update the deployment target, unable to adapt the updates anymore.

Instead, we should let the developers do this themself.

So I just the v6.1.2, which reverted this PR. And if you're going to submit it to the app store, please follow the guide on the readme.

**Comment by vomchik** [comment]
@plrthink thank you!

**Pull request merged**
