### PR TITLE
Fixed conflict with Appodeal

### PR DESCRIPTION
**Pull request by kurtsergey**
duplicate symbol _zipOpen4 in:
    /ios/Pods/Appodeal/APDVungleAdapter.embeddedframework/VungleSDK.framework/VungleSDK(vungle_zip.o)

### CODE REVIEW

**Comment by kurtsergey** [comment]
@plrthink Would you please publish release?

**Comment by plrthink** [comment]
@kurtsergey published under 3.0.0 as introduced break changes.

**Comment by kurtsergey** [comment]
@plrthink Thanks for release.
Please create tag also for consistency and provide breaking changes description.

**Comment by plrthink** [comment]
@kurtsergey has updated the release note, you can review at here https://github.com/mockingbot/react-native-zip-archive/releases/tag/v3.0.0

**Comment by kurtsergey** [comment]
@plrthink Thanks you a lot!

**Pull request merged**
