### PR TITLE
- Add support windows build (react-native-windows@current)

### PR DESCRIPTION
**Pull request by legion-zver**
Create from tag 4.1.5

### CODE REVIEW

**Comment by plrthink** [comment]
Wow, cool, but I have a question on this. Can I merge this into the master branch which adopted to the react-native@>0.60.0? I'm not familiar with the react-native-windows so is it safe to do that? Does that would still work on your use case?

**Comment by legion-zver** [comment]
@plrthink I can check it and make a new pull request) I just use version RN 0.59.10 in projects, so I implemented support based on version 4.1.5 react-native-zip-archive)))

**Comment by plrthink** [comment]
It would be awesome if you can rebase this PR on the master branch.

**Comment by plrthink** [comment]
@legion-zver Any update on this? Is there something I help you with to make this based on version 5.0.0 which is on the current master branch? If we can rebase this on the master branch I would merge it.

**Pull request closed without merging**
